apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: webapp-app
  replicas: 3 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: webapp-app
    spec:
      containers:
      - name: webapp-app
        image: kastellanos/webapp:1.0
        ports:
        - containerPort: 5656
          name: server
